# Generated by Django 3.0.8 on 2020-10-18 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bursaryapplicant',
            old_name='county',
            new_name='County',
        ),
        migrations.RenameField(
            model_name='bursaryapplicant',
            old_name='dob',
            new_name='Date_Of_Birth',
        ),
        migrations.RenameField(
            model_name='bursaryapplicant',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='bursaryapplicant',
            old_name='ID_number',
            new_name='ID_Number',
        ),
        migrations.RenameField(
            model_name='bursaryapplicant',
            old_name='phone_number',
            new_name='Phone_number',
        ),
        migrations.RenameField(
            model_name='bursaryapplicant',
            old_name='kra_pin',
            new_name='Sub_location',
        ),
        migrations.RenameField(
            model_name='bursaryapplicant',
            old_name='ward',
            new_name='Ward',
        ),
        migrations.RenameField(
            model_name='bursaryapplicant',
            old_name='zip_code',
            new_name='Zip_Code',
        ),
    ]
