# Generated by Django 3.0.8 on 2020-10-18 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0003_auto_20201018_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bursaryapplicant',
            name='ID_number',
        ),
    ]
