# Generated by Django 3.0.8 on 2020-10-18 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0004_remove_bursaryapplicant_id_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bursaryapplicant',
            old_name='Zip_Code',
            new_name='Zip_code',
        ),
    ]
