# Generated by Django 3.0.8 on 2020-10-18 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0005_auto_20201018_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bursaryapplicant',
            old_name='Date_Of_Birth',
            new_name='Date_of_birth',
        ),
    ]
