# Generated by Django 3.0.8 on 2020-10-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0006_auto_20201018_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bursaryapplicant',
            name='Date_of_birth',
            field=models.CharField(max_length=20),
        ),
    ]
