# Generated by Django 3.0.8 on 2020-10-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0007_auto_20201018_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='bursaryapplicant',
            name='ID_number',
            field=models.CharField(default='0000000000', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bursaryapplicant',
            name='Zip_code',
            field=models.CharField(max_length=20),
        ),
    ]
