# Generated by Django 3.0.8 on 2020-10-31 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0010_auto_20201023_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='bursaryapplicant',
            name='first_name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='bursary_applicant', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bursaryapplicant',
            name='name',
            field=models.CharField(default='testuser', max_length=200),
            preserve_default=False,
        ),
    ]
