# Generated by Django 3.0.8 on 2020-10-31 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0011_auto_20201101_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='t', max_length=100),
            preserve_default=False,
        ),
    ]
