# Generated by Django 3.0.8 on 2020-11-01 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0014_auto_20201101_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bursaryapplicant',
            name='first_name',
        ),
    ]
