# Generated by Django 3.0.8 on 2020-11-01 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0015_remove_bursaryapplicant_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bursaryapplicant',
            name='first_name',
            field=models.CharField(default='p', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bursaryapplicant',
            name='last_name',
            field=models.CharField(default='o', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bursaryapplicant',
            name='middle_name',
            field=models.CharField(default='q', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submittedapplicationsmodel',
            name='first_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibursary_accounts.BursaryApplicant'),
        ),
    ]
