# Generated by Django 3.0.8 on 2020-11-04 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0016_auto_20201101_0448'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewApplicationModel',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ibursary_accounts.BursaryApplicant')),
                ('family_type', models.CharField(max_length=100)),
                ('guardian_for_orphan', models.CharField(max_length=100)),
                ('wishers_for_orphan', models.CharField(max_length=100)),
                ('other_for_orphan', models.CharField(max_length=100)),
                ('other_orphan_text', models.CharField(max_length=100)),
                ('fund_beneficiary_before', models.CharField(max_length=100)),
                ('fund_amount', models.CharField(max_length=100)),
                ('fund_source', models.CharField(max_length=100)),
                ('p_first_name', models.CharField(max_length=100)),
                ('p_middle_name', models.CharField(max_length=100)),
                ('p_last_name', models.CharField(max_length=100)),
                ('p_employed', models.CharField(max_length=100)),
                ('p_education', models.CharField(max_length=100)),
                ('p_occupation', models.CharField(max_length=100)),
                ('p_phone', models.CharField(max_length=100)),
                ('p_nhif', models.CharField(max_length=100)),
                ('p_id', models.CharField(max_length=100)),
                ('p_pension_income', models.CharField(max_length=100)),
                ('p_relief_income', models.CharField(max_length=100)),
                ('p_business_income', models.CharField(max_length=100)),
                ('p_farming_income', models.CharField(max_length=100)),
                ('p_private_groups_income', models.CharField(max_length=100)),
                ('p_well_wishers_income', models.CharField(max_length=100)),
                ('p_casual_labour_income', models.CharField(max_length=100)),
                ('p_other_income', models.CharField(max_length=100)),
            ],
        ),
    ]
