# Generated by Django 3.0.8 on 2020-11-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0017_newapplicationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='newapplicationmodel',
            name='class_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newapplicationmodel',
            name='course',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newapplicationmodel',
            name='dob',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newapplicationmodel',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newapplicationmodel',
            name='institution',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newapplicationmodel',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newapplicationmodel',
            name='middle_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newapplicationmodel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newapplicationmodel',
            name='outstanding_sec_fee',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newapplicationmodel',
            name='outstanding_university_fee',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newapplicationmodel',
            name='paid_sec_fee',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newapplicationmodel',
            name='paid_university_fee',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newapplicationmodel',
            name='school',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newapplicationmodel',
            name='school_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newapplicationmodel',
            name='sec_reg_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newapplicationmodel',
            name='sec_year',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newapplicationmodel',
            name='secondary_school_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newapplicationmodel',
            name='sub_county',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newapplicationmodel',
            name='total_sec_fee',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newapplicationmodel',
            name='total_university_fee',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newapplicationmodel',
            name='university_reg_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newapplicationmodel',
            name='university_year',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newapplicationmodel',
            name='value',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newapplicationmodel',
            name='village',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newapplicationmodel',
            name='ward',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newapplicationmodel',
            name='year',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
