# Generated by Django 3.0.8 on 2020-11-05 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0018_auto_20201104_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='newapplicationmodel',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newapplicationmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibursary_accounts.BursaryApplicant'),
        ),
    ]
