# Generated by Django 3.0.8 on 2020-11-05 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0021_auto_20201105_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newapplicationmodel',
            name='family_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newapplicationmodel',
            name='fund_amount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newapplicationmodel',
            name='fund_beneficiary_before',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newapplicationmodel',
            name='fund_source',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newapplicationmodel',
            name='guardian_for_orphan',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newapplicationmodel',
            name='other_for_orphan',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newapplicationmodel',
            name='other_orphan_text',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newapplicationmodel',
            name='p_business_income',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newapplicationmodel',
            name='p_casual_labour_income',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newapplicationmodel',
            name='p_education',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newapplicationmodel',
            name='p_employed',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newapplicationmodel',
            name='p_farming_income',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newapplicationmodel',
            name='p_first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newapplicationmodel',
            name='p_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newapplicationmodel',
            name='p_last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newapplicationmodel',
            name='p_middle_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newapplicationmodel',
            name='p_nhif',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newapplicationmodel',
            name='p_occupation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newapplicationmodel',
            name='p_other_income',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newapplicationmodel',
            name='p_pension_income',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newapplicationmodel',
            name='p_phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newapplicationmodel',
            name='p_private_groups_income',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newapplicationmodel',
            name='p_relief_income',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newapplicationmodel',
            name='p_well_wishers_income',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newapplicationmodel',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ibursary_accounts.BursaryApplicant'),
        ),
        migrations.AlterField(
            model_name='newapplicationmodel',
            name='wishers_for_orphan',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
