# Generated by Django 3.0.8 on 2020-11-07 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0024_auto_20201107_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedapplicationsmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
