# Generated by Django 3.0.8 on 2020-11-08 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0026_auto_20201107_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newapplicationmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibursary_accounts.BursaryApplicant'),
        ),
    ]
