# Generated by Django 3.0.8 on 2020-11-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0028_auto_20201109_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bursaryapplicant',
            name='Sub_location',
        ),
        migrations.AddField(
            model_name='bursaryapplicant',
            name='Sub_County',
            field=models.CharField(default='Ruiru', max_length=100),
        ),
        migrations.AlterField(
            model_name='bursaryapplicant',
            name='Ward',
            field=models.CharField(default='Kahawa Wendani', max_length=20),
        ),
    ]
