# Generated by Django 3.0.8 on 2020-11-24 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0029_auto_20201124_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newapplicationmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bursary_applicant', to='ibursary_accounts.BursaryApplicant'),
        ),
    ]
