# Generated by Django 3.0.8 on 2020-12-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0030_auto_20201124_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=100)),
                ('reg', models.CharField(max_length=100)),
            ],
        ),
    ]
