# Generated by Django 3.0.8 on 2021-01-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0031_trialmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialmodel',
            name='chief',
            field=models.FileField(default='fi', upload_to='files'),
        ),
    ]
