# Generated by Django 3.0.8 on 2021-02-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0032_trialmodel_chief'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialmodel',
            name='business_income',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='casual_labour_income',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='farming_income',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='fund_source',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='fund_source_amount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='other_income',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='outstanding_balance',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='paid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='pension_income',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='private_groups_income',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='relief_income',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='total_fee',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='well_wishers_income',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='year_of_study',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
