# Generated by Django 3.0.8 on 2021-02-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0033_auto_20210209_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialmodel',
            name='guardian_as_financier',
            field=models.BooleanField(default=False),
        ),
    ]
