# Generated by Django 3.0.8 on 2021-02-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0034_trialmodel_guardian_as_financier'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialmodel',
            name='other_financier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='well_wishers_as_financier',
            field=models.BooleanField(default=False),
        ),
    ]
