# Generated by Django 3.0.8 on 2021-02-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0036_trialmodel_other_financiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialmodel',
            name='chief_document',
            field=models.FileField(default='fi', upload_to='files'),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='chief_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='clergy_document',
            field=models.FileField(default='fi', upload_to='files'),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='clergy_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='father_gross_income',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='fee_slip_document',
            field=models.FileField(default='fi', upload_to='files'),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='fee_structure_document',
            field=models.FileField(default='fi', upload_to='files'),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='fourth_sibling_balance',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='fourth_sibling_class',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='fourth_sibling_fee_paid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='fourth_sibling_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='fourth_sibling_school',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='fourth_sibling_total_fee',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='guardian_children',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='guardian_gross_income',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='mca_document',
            field=models.FileField(default='fi', upload_to='files'),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='mca_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='mother_gross_income',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='number_of_siblings',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='p_education_level',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='p_employed',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='p_first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='p_id_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='p_last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='p_middle_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='p_nhif',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='p_occupation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='p_phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='parent_guardian_declaration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='school_document',
            field=models.FileField(default='fi', upload_to='files'),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='school_rep_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='second_sibling_balance',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='second_sibling_class',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='second_sibling_fee_paid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='second_sibling_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='second_sibling_school',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='second_sibling_total_fee',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='sibling_balance',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='sibling_class',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='sibling_f_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='sibling_fee_paid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='sibling_school',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='sibling_total_fee',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='siblings_in_post_secondary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='siblings_in_secondary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='student_declaration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='third_sibling_balance',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='third_sibling_class',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='third_sibling_fee_paid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='third_sibling_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='third_sibling_school',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='third_sibling_total_fee',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='transcript_document',
            field=models.FileField(default='fi', upload_to='files'),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='working_siblings',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
