# Generated by Django 3.0.8 on 2021-02-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0037_auto_20210211_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialmodel',
            name='benefitted',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
