# Generated by Django 3.0.8 on 2021-02-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0038_auto_20210211_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialmodel',
            name='chief_document',
            field=models.FileField(default='fi', upload_to='chief_docs'),
        ),
        migrations.AlterField(
            model_name='trialmodel',
            name='clergy_document',
            field=models.FileField(default='fi', upload_to='religious_leader_docs'),
        ),
        migrations.AlterField(
            model_name='trialmodel',
            name='fee_slip_document',
            field=models.FileField(default='fi', upload_to='fee_slip_docs'),
        ),
        migrations.AlterField(
            model_name='trialmodel',
            name='fee_structure_document',
            field=models.FileField(default='fi', upload_to='fee_structure_docs'),
        ),
        migrations.AlterField(
            model_name='trialmodel',
            name='mca_document',
            field=models.FileField(default='fi', upload_to='mca_docs'),
        ),
        migrations.AlterField(
            model_name='trialmodel',
            name='school_document',
            field=models.FileField(default='fi', upload_to='school_docs'),
        ),
        migrations.AlterField(
            model_name='trialmodel',
            name='transcript_document',
            field=models.FileField(default='fi', upload_to='transcript_docs'),
        ),
    ]
