# Generated by Django 3.0.8 on 2021-02-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0040_remove_trialmodel_chief'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialmodel',
            name='school_admitted',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='school_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
