# Generated by Django 3.0.8 on 2021-02-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0042_auto_20210211_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialmodel',
            name='chief_document',
            field=models.FileField(default='fi', upload_to='media/chief_docs'),
        ),
        migrations.AlterField(
            model_name='trialmodel',
            name='clergy_document',
            field=models.FileField(default='fi', upload_to='media/religious_leader_docs'),
        ),
        migrations.AlterField(
            model_name='trialmodel',
            name='fee_slip_document',
            field=models.FileField(default='fi', upload_to='media/fee_slip_docs'),
        ),
        migrations.AlterField(
            model_name='trialmodel',
            name='fee_structure_document',
            field=models.FileField(default='fi', upload_to='media/fee_structure_docs'),
        ),
        migrations.AlterField(
            model_name='trialmodel',
            name='mca_document',
            field=models.FileField(default='fi', upload_to='media/mca_docs'),
        ),
        migrations.AlterField(
            model_name='trialmodel',
            name='school_document',
            field=models.FileField(default='fi', upload_to='media/school_docs'),
        ),
        migrations.AlterField(
            model_name='trialmodel',
            name='transcript_document',
            field=models.FileField(default='fi', upload_to='media/transcript_docs'),
        ),
    ]
