# Generated by Django 3.0.8 on 2021-02-14 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0044_auto_20210211_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialmodel',
            name='first_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_first_trialmodel', to='ibursary_accounts.BursaryApplicant', unique=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='last_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_last_trialmodel', to='ibursary_accounts.BursaryApplicant', unique=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='middle_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_second_trialmodel', to='ibursary_accounts.BursaryApplicant', unique=True),
        ),
    ]
