# Generated by Django 3.0.8 on 2021-02-15 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0047_auto_20210214_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialmodel',
            name='first_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_first_trialmodel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trialmodel',
            name='last_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_last_name', to='ibursary_accounts.BursaryApplicant'),
        ),
        migrations.AlterField(
            model_name='trialmodel',
            name='middle_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_second_trialmodel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trialmodel',
            name='phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_Phone_number', to='ibursary_accounts.BursaryApplicant'),
        ),
    ]
