# Generated by Django 3.0.8 on 2021-02-16 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0051_auto_20210216_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bursaryapplicant',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trialmodel',
            name='first_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ann', to='ibursary_accounts.BursaryApplicant'),
        ),
    ]
