# Generated by Django 3.0.8 on 2021-02-16 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0052_auto_20210216_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trialmodel',
            old_name='first_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='trialmodel',
            old_name='last_name',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='trialmodel',
            old_name='middle_name',
            new_name='mname',
        ),
    ]
