# Generated by Django 3.0.8 on 2021-02-16 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0055_auto_20210216_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bursaryapplicant',
            name='Zip_code',
        ),
        migrations.RemoveField(
            model_name='trialmodel',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='trialmodel',
            name='mname',
        ),
        migrations.RemoveField(
            model_name='trialmodel',
            name='phone',
        ),
        migrations.AddField(
            model_name='bursaryapplicant',
            name='Sub_location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trialmodel',
            name='fname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bursaryapplicant', to='ibursary_accounts.BursaryApplicant'),
        ),
    ]
