# Generated by Django 3.0.8 on 2021-02-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0056_auto_20210216_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialmodel',
            name='disability',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
