# Generated by Django 3.0.8 on 2021-02-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0057_trialmodel_disability'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialmodel',
            name='disability_form',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
