# Generated by Django 3.0.8 on 2021-02-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0059_auto_20210217_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trialmodel',
            name='fourth_sibling_balance',
        ),
        migrations.RemoveField(
            model_name='trialmodel',
            name='fourth_sibling_class',
        ),
        migrations.RemoveField(
            model_name='trialmodel',
            name='fourth_sibling_fee_paid',
        ),
        migrations.RemoveField(
            model_name='trialmodel',
            name='fourth_sibling_name',
        ),
        migrations.RemoveField(
            model_name='trialmodel',
            name='fourth_sibling_school',
        ),
        migrations.RemoveField(
            model_name='trialmodel',
            name='fourth_sibling_total_fee',
        ),
        migrations.RemoveField(
            model_name='trialmodel',
            name='second_sibling_balance',
        ),
        migrations.RemoveField(
            model_name='trialmodel',
            name='second_sibling_class',
        ),
        migrations.RemoveField(
            model_name='trialmodel',
            name='second_sibling_fee_paid',
        ),
        migrations.RemoveField(
            model_name='trialmodel',
            name='second_sibling_name',
        ),
        migrations.RemoveField(
            model_name='trialmodel',
            name='second_sibling_school',
        ),
        migrations.RemoveField(
            model_name='trialmodel',
            name='second_sibling_total_fee',
        ),
        migrations.RemoveField(
            model_name='trialmodel',
            name='sibling_balance',
        ),
        migrations.RemoveField(
            model_name='trialmodel',
            name='sibling_class',
        ),
        migrations.RemoveField(
            model_name='trialmodel',
            name='sibling_f_name',
        ),
        migrations.RemoveField(
            model_name='trialmodel',
            name='sibling_fee_paid',
        ),
        migrations.RemoveField(
            model_name='trialmodel',
            name='sibling_school',
        ),
        migrations.RemoveField(
            model_name='trialmodel',
            name='sibling_total_fee',
        ),
        migrations.RemoveField(
            model_name='trialmodel',
            name='third_sibling_balance',
        ),
        migrations.RemoveField(
            model_name='trialmodel',
            name='third_sibling_class',
        ),
        migrations.RemoveField(
            model_name='trialmodel',
            name='third_sibling_fee_paid',
        ),
        migrations.RemoveField(
            model_name='trialmodel',
            name='third_sibling_name',
        ),
        migrations.RemoveField(
            model_name='trialmodel',
            name='third_sibling_school',
        ),
        migrations.RemoveField(
            model_name='trialmodel',
            name='third_sibling_total_fee',
        ),
    ]
