# Generated by Django 3.0.8 on 2021-02-19 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0060_auto_20210217_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialmodel',
            name='user',
            field=models.OneToOneField(blank=True, limit_choices_to={'is_bursaryapplicant': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
