# Generated by Django 3.0.8 on 2021-02-19 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0062_auto_20210219_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trialmodel',
            old_name='user',
            new_name='candidate',
        ),
    ]
