# Generated by Django 3.0.8 on 2021-02-19 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0063_auto_20210219_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trialmodel',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='trialmodel',
            name='fname',
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='gender',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='middle_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='trialmodel',
            name='user',
            field=models.OneToOneField(blank=True, limit_choices_to={'is_bursaryapplicant': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
