# Generated by Django 3.0.8 on 2021-03-05 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0064_auto_20210219_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialmodel',
            name='first_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ibursary_accounts.BursaryApplicant'),
        ),
        migrations.AlterField(
            model_name='trialmodel',
            name='gender',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
