# Generated by Django 3.0.8 on 2021-03-05 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0066_auto_20210306_0216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bursaryapplicant',
            old_name='full_name',
            new_name='applicant_full_name',
        ),
    ]
