# Generated by Django 3.0.8 on 2021-03-06 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0067_auto_20210306_0230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='applicant_full_name',
        ),
    ]
