# Generated by Django 3.0.8 on 2021-03-14 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0068_auto_20210306_0300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trialmodel',
            old_name='applicant_full_name',
            new_name='first_name',
        ),
    ]
