# Generated by Django 3.0.8 on 2021-03-14 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0069_auto_20210314_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bursaryapplicant',
            name='applicant_full_name',
        ),
    ]
