# Generated by Django 3.0.8 on 2021-03-15 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0073_trialmodel_model_recommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trialmodel',
            name='first_name',
        ),
    ]
