# Generated by Django 3.0.8 on 2021-03-15 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0074_remove_trialmodel_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialmodel',
            name='school_admitted',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trialmodel',
            name='user',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_bursaryapplicant': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
