# Generated by Django 3.0.8 on 2021-03-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0076_auto_20210317_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialmodel',
            name='institution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trialmodel',
            name='reg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
