# Generated by Django 3.0.8 on 2021-03-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0078_auto_20210320_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialmodel',
            name='Bursary_Application_Status',
            field=models.CharField(blank=True, default='UNDER REVIEW', max_length=100, null=True),
        ),
    ]
