# Generated by Django 3.0.8 on 2021-03-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0080_auto_20210320_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialmodel',
            name='amount_allocated',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
