# Generated by Django 3.0.8 on 2021-03-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0081_trialmodel_amount_allocated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialmodel',
            name='Bursary_Application_Status',
            field=models.CharField(default='REVIEW_IN_PROCESS', max_length=100),
        ),
    ]
