# Generated by Django 3.0.8 on 2021-03-20 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0082_auto_20210320_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialmodel',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ibursary_accounts.BursaryApplicant'),
        ),
        migrations.AlterField(
            model_name='trialmodel',
            name='guardian_children',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
