# Generated by Django 3.0.8 on 2021-03-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibursary_accounts', '0083_auto_20210321_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='applicant_full_name',
        ),
        migrations.AddField(
            model_name='user',
            name='ward',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
